In [ ]:
import pandas as pd

# Читаем CSV в датафрейм (таблицу). Путь ../ — на уровень вверх из notebooks/ в data/
df = pd.read_csv("../data/paysim.csv")

df.shape

(6362620, 11)

In [ ]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            str
 2   amount          float64
 3   nameOrig        str
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        str
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), str(3)
memory usage: 534.0 MB

In [ ]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [ ]:
# Считаем метку isFraud 
print(df['isFraud'].value_counts())                
print(df['isFraud'].value_counts(normalize=True))

isFraud
0    6354407
1       8213
Name: count, dtype: int64
isFraud
0    0.998709
1    0.001291
Name: proportion, dtype: float64

In [ ]:
# Таблица 
pd.crosstab(df['type'], df['isFraud'], margins=True)

isFraud         0     1      All
type
CASH_IN   1399284     0  1399284
CASH_OUT  2233384  4116  2237500
DEBIT       41432     0    41432
PAYMENT   2151495     0  2151495
TRANSFER   528812  4097   532909
All       6354407  8213  6362620

In [7]:
# Оставляем только типы операций, где встречается фрод
fraud_types = ['TRANSFER', 'CASH_OUT']
df_model = df[df['type'].isin(fraud_types)]

print("Было строк:      ", len(df))
print("Стало строк:     ", len(df_model))
print("Доля фрода стала:", df_model['isFraud'].mean())

Было строк:       6362620
Стало строк:      2770409
Доля фрода стала: 0.002964544224336551